services:
  game-nginx:
    image: nginx:alpine
    container_name: game-nginx
    ports:
      - "5001:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - game-php

  game-php:
    build:
      context: ./docker/php
    container_name: game-php
    volumes:
      - ./:/app