version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: game-nginx
    ports:
      - "5000:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    container_name: game-php
    volumes:
      - ./:/app